(() => {
    const battleModules = window.EchoesOfTheCityBattleModules || (window.EchoesOfTheCityBattleModules = {});
    const battleDefinitions = battleModules.battleDefinitions || (battleModules.battleDefinitions = {});

    const vergiliusSprites = {
        idle: 'assets/debugsprites/Vergilius_Idle_Sprite.png',
        moving: 'assets/debugsprites/Vergilius_Moving_Sprite.png',
        hurt: 'assets/debugsprites/Vergilius_Hurt_Sprite.png',
        guard: 'assets/debugsprites/Vergilius_Guard_Sprite.png',
        evade: 'assets/debugsprites/Vergilius_Evade_Sprite.png',
        skills: {
            'heated-puncture': 'assets/debugsprites/Vergilius_Skill_1.gif',
            'scorching-incision': 'assets/debugsprites/Vergilius_Skill_2.gif',
            'following-the-flow': 'assets/debugsprites/Vergilius_Skill_3.gif',
            'draw-of-the-sword': 'assets/debugsprites/Vergilius_Skill_1.gif',
            acupuncture: 'assets/debugsprites/Vergilius_Skill_2.gif',
            'yield-my-flesh': 'assets/debugsprites/Vergilius_Skill_3.gif',
            'to-claim-their-bones': 'assets/debugsprites/Vergilius_Skill_3.gif',
        },
    };

    const kimSprites = {
        idle: 'assets/debugsprites/Bamboo-hatted_Kim_Idle_Sprite.png',
        moving: 'assets/debugsprites/Bamboo-hatted_Kim_Moving_Sprite.png',
        hurt: 'assets/debugsprites/Bamboo-hatted_Kim_Hurt_Sprite.png',
        skills: { ...vergiliusSprites.skills },
    };

    const dongbaekSprites = {
        idle: 'assets/debugsprites/Lobotomy_E.G.O_Sunshower_-_Dongbaek_Idle_Sprite.png',
        moving: 'assets/debugsprites/Lobotomy_E.G.O_Sunshower_-_Dongbaek_Moving_Sprite.png',
        hurt: 'assets/debugsprites/Lobotomy_E.G.O_Sunshower_-_Dongbaek_Hurt_Sprite.png',
        skills: { ...vergiliusSprites.skills },
    };

    const hongLuSprites = {
        idle: 'assets/debugsprites/The_Ring_Nursefather_-_Callisto_Idle_Sprite.png',
        moving: 'assets/debugsprites/The_Ring_Nursefather_-_Callisto_Moving_Sprite.png',
        hurt: 'assets/debugsprites/The_Ring_Nursefather_-_Callisto_Hurt_Sprite.png',
        skills: {
            anatomize: 'assets/debugsprites/The_House_of_Spiders_The_Ring_Nursefather_Hong_Lu_Skill_1.gif',
            'gather-ingredient-blood-bathed-objet': 'assets/debugsprites/The_House_of_Spiders_The_Ring_Nursefather_Hong_Lu_Skill_2.gif',
            'tibias-melody': 'assets/debugsprites/The_House_of_Spiders_The_Ring_Nursefather_Hong_Lu_Skill_3.gif',
            'stinging-memories': 'assets/debugsprites/The_House_of_Spiders_The_Ring_Nursefather_Hong_Lu_Skill_1.gif',
            'aching-heart': 'assets/debugsprites/The_House_of_Spiders_The_Ring_Nursefather_Hong_Lu_Skill_2.gif',
            'sink-it-all': 'assets/debugsprites/The_House_of_Spiders_The_Ring_Nursefather_Hong_Lu_Skill_3.gif',
        },
    };

    const debugFightDefinition = {
        playerUnits: [
            {
                id: 'vergilius',
                name: 'Vergilius',
                level: 50,
                maxHp: 392,
                sp: 0,
                speedRange: [4, 8],
                defenseLevel: 50,
                staggerThresholds: [0.66, 0.33],
                resistances: {
                    physical: {
                        slash: 1,
                        pierce: 1,
                        blunt: 1,
                    },
                    sin: {
                        wrath: 1,
                        lust: 1,
                        sloth: 1,
                        gluttony: 1,
                        gloom: 1,
                        pride: 1,
                        envy: 1,
                    },
                },
                sprites: vergiliusSprites,
                skills: [
                    {
                        id: 'heated-puncture',
                        name: 'Heated Puncture',
                        basePower: 14,
                        coinPower: 2,
                        coinCount: 3,
                        damageType: 'slash',
                        sinType: 'wrath',
                        offenseLevel: 0,
                        effects: [
                            { trigger: 'onHit', type: 'applyStatus', statusId: 'burn', potency: 3, count: 1 },
                        ],
                        borderPath: 'assets/skillborders/Wrath1.png',
                        description: 'Vergilius Skill 1. Inflicts Burn on hit.',
                    },
                    {
                        id: 'scorching-incision',
                        name: 'Scorching Incision',
                        basePower: 15,
                        coinPower: 2,
                        coinCount: 3,
                        damageType: 'slash',
                        sinType: 'wrath',
                        offenseLevel: 1,
                        effects: [
                            { trigger: 'onHit', type: 'applyStatus', statusId: 'burn', potency: 4, count: 1 },
                        ],
                        borderPath: 'assets/skillborders/Wrath2.png',
                        description: 'Vergilius Skill 2. Stronger clash route with Burn.',
                    },
                    {
                        id: 'following-the-flow',
                        name: 'Following the Flow',
                        basePower: 18,
                        coinPower: 2,
                        coinCount: 3,
                        damageType: 'slash',
                        sinType: 'wrath',
                        offenseLevel: 2,
                        effects: [
                            { trigger: 'onHit', type: 'applyStatus', statusId: 'burn', potency: 5, count: 2 },
                        ],
                        borderPath: 'assets/skillborders/Wrath3.png',
                        description: 'Vergilius Skill 3. Highest base power among his starter kit.',
                    },
                    {
                        id: 'vergilius-evade',
                        name: 'Evade',
                        skillType: 'evade',
                        basePower: 14,
                        coinPower: 8,
                        coinCount: 1,
                        sinType: 'wrath',
                        offenseLevel: 0,
                        borderPath: 'assets/skillborders/Wrath1.png',
                        description: 'Defense Skill. Reactively dodges incoming coins while its final power holds.',
                    },
                ],
            },
            {
                id: 'bamboo-hatted-kim',
                name: 'Bamboo-Hatted Kim',
                level: 50,
                maxHp: 366,
                sp: 0,
                speedRange: [4, 7],
                defenseLevel: 49,
                staggerThresholds: [0.66, 0.33],
                resistances: {
                    physical: {
                        slash: 0.5,
                        pierce: 1,
                        blunt: 2,
                    },
                    sin: {
                        wrath: 1,
                        lust: 2,
                        sloth: 1,
                        gluttony: 2,
                        gloom: 1,
                        pride: 0.75,
                        envy: 1,
                    },
                },
                sprites: kimSprites,
                skills: [
                    {
                        id: 'draw-of-the-sword',
                        name: 'Draw of the Sword',
                        basePower: 10,
                        coinPower: 4,
                        coinCount: 4,
                        damageType: 'slash',
                        sinType: 'pride',
                        offenseLevel: 0,
                        borderPath: 'assets/skillborders/Pride1.png',
                        description: 'Skill 1. Builds Poise Count, gains Poise on use, and bleeds targets on later coins.',
                    },
                    {
                        id: 'acupuncture',
                        name: 'Acupuncture',
                        basePower: 12,
                        coinPower: 4,
                        coinCount: 4,
                        damageType: 'slash',
                        sinType: 'pride',
                        offenseLevel: 1,
                        borderPath: 'assets/skillborders/Pride2.png',
                        description: 'Skill 2. Poise-positive slash chain with escalating critical payoff.',
                    },
                    {
                        id: 'yield-my-flesh',
                        name: 'Yield My Flesh',
                        basePower: 30,
                        coinPower: -8,
                        coinCount: 1,
                        damageType: 'slash',
                        sinType: 'pride',
                        offenseLevel: 2,
                        targeting: 'highestMaxPower',
                        borderPath: 'assets/skillborders/Pride3.png',
                        description: 'Skill 3.',
                    },
                    {
                        id: 'to-claim-their-bones',
                        name: 'To Claim Their Bones',
                        basePower: 16,
                        coinPower: 4,
                        coinCount: 4,
                        damageType: 'slash',
                        sinType: 'pride',
                        offenseLevel: 2,
                        borderPath: 'assets/skillborders/Pride3.png',
                        description: 'Skill 3-2. Follow-up slash finisher that consumes all Poise at attack end.',
                    },
                    {
                        id: 'kim-counter',
                        name: 'Counter',
                        skillType: 'counter',
                        basePower: 12,
                        coinPower: 4,
                        coinCount: 1,
                        damageType: 'slash',
                        sinType: 'pride',
                        offenseLevel: 0,
                        borderPath: 'assets/skillborders/Pride1.png',
                        description: 'Defense Skill. Reactively launches a one-sided counterattack after being hit.',
                    },
                ],
            },
        ],
        enemyUnits: [
            {
                id: 'ring-nursefather-hong-lu',
                name: 'The Ring Nursefather Callisto',
                level: 50,
                maxHp: 428,
                sp: 0,
                speedRange: [3, 7],
                defenseLevel: 50,
                staggerThresholds: [0.75, 0.5, 0.25],
                resistances: {
                    physical: {
                        slash: 0.8,
                        pierce: 1,
                        blunt: 1.2,
                    },
                    sin: {
                        wrath: 1,
                        lust: 0.8,
                        sloth: 1.2,
                        gluttony: 1.2,
                        gloom: 0.8,
                        pride: 1,
                        envy: 1,
                    },
                },
                sprites: hongLuSprites,
                skills: [
                    {
                        id: 'anatomize',
                        name: 'Anatomize',
                        basePower: 6,
                        coinPower: 6,
                        coinCount: 2,
                        damageType: 'slash',
                        sinType: 'envy',
                        offenseLevel: 0,
                        borderPath: 'assets/skillborders/Envy1.png',
                        description: 'Hong Lu Skill 1. Two heavy-value slash coins.',
                    },
                    {
                        id: 'gather-ingredient-blood-bathed-objet',
                        name: 'Gather Ingredient Blood-bathed Objet',
                        basePower: 7,
                        coinPower: 7,
                        coinCount: 2,
                        damageType: 'slash',
                        sinType: 'envy',
                        offenseLevel: 1,
                        borderPath: 'assets/skillborders/Envy2.png',
                        description: 'Hong Lu Skill 2. High-variance two-coin clash.',
                    },
                    {
                        id: 'tibias-melody',
                        name: "Tibia's Melody Anatomization of the Unatomized by the Anatomized",
                        basePower: 10,
                        coinPower: 4,
                        coinCount: 4,
                        damageType: 'slash',
                        sinType: 'envy',
                        offenseLevel: 2,
                        borderPath: 'assets/skillborders/Envy3.png',
                        description: 'Hong Lu Skill 3. Long clash route for the second enemy slot.',
                    },
                ],
            },
            {
                id: 'dongbaek',
                name: 'Dongbaek',
                level: 50,
                maxHp: 402,
                sp: 0,
                speedRange: [3, 7],
                defenseLevel: 49,
                staggerThresholds: [0.75, 0.5, 0.25],
                resistances: {
                    physical: {
                        slash: 1,
                        pierce: 1,
                        blunt: 1.5,
                    },
                    sin: {
                        wrath: 0.5,
                        lust: 0.5,
                        sloth: 1,
                        gluttony: 1,
                        gloom: 2,
                        pride: 1.5,
                        envy: 1,
                    },
                },
                sprites: dongbaekSprites,
                skills: [
                    {
                        id: 'stinging-memories',
                        name: 'Stinging Memories',
                        basePower: 3,
                        coinPower: 3,
                        coinCount: 3,
                        damageType: 'slash',
                        sinType: 'gloom',
                        offenseLevel: 0,
                        borderPath: 'assets/skillborders/Gloom1.png',
                        description: 'Skill 1. Positive-coin sinker that inflicts Sinking and Rupture on every coin.',
                    },
                    {
                        id: 'aching-heart',
                        name: 'Aching Heart',
                        basePower: 13,
                        coinPower: -4,
                        coinCount: 2,
                        damageType: 'slash',
                        sinType: 'gloom',
                        offenseLevel: 1,
                        borderPath: 'assets/skillborders/Gloom2.png',
                        description: 'Skill 2. Minus-coin slash that stacks Rupture on hit.',
                    },
                    {
                        id: 'sink-it-all',
                        name: 'Sink It All',
                        basePower: 26,
                        coinPower: -10,
                        coinCount: 1,
                        damageType: 'slash',
                        sinType: 'gloom',
                        offenseLevel: 2,
                        borderPath: 'assets/skillborders/Gloom3.png',
                        description: 'Skill 3. Self-Sinking opener with a heavy SP hit and Sinking application.',
                    },
                ],
            },
        ],
    };

    battleDefinitions.debugFight = debugFightDefinition;
    battleModules.debugFightTemplate = debugFightDefinition;
    battleModules.defaultBattleDefinition = battleModules.defaultBattleDefinition || debugFightDefinition;
})();
