(() => {
    const battleModules = window.EchoesOfTheCityBattleModules || (window.EchoesOfTheCityBattleModules = {});
    const registerUnitDefinition = battleModules.content?.registerUnitDefinition;

    if (typeof registerUnitDefinition !== 'function') {
        throw new Error('Battle content registry is not available.');
    }

    const bambooHattedKimDefinition = {
        id: 'bamboo-hatted-kim',
        name: 'Bamboo-Hatted Kim',
        level: 50,
        maxHp: 366,
        sp: 0,
        speedRange: [4, 7],
        defenseLevel: 49,
        staggerThresholds: [0.66, 0.33],
        resistances: {
            physical: {
                slash: 0.5,
                pierce: 1,
                blunt: 2,
            },
            sin: {
                wrath: 1,
                lust: 2,
                sloth: 1,
                gluttony: 2,
                gloom: 1,
                pride: 0.75,
                envy: 1,
            },
        },
        sprites: {
            idle: 'assets/debugsprites/Bamboo-hatted_Kim_Idle_Sprite.png',
            moving: 'assets/debugsprites/Bamboo-hatted_Kim_Moving_Sprite.png',
            hurt: 'assets/debugsprites/Bamboo-hatted_Kim_Hurt_Sprite.png',
            skills: {
                'heated-puncture': 'assets/debugsprites/Vergilius_Skill_1.gif',
                'scorching-incision': 'assets/debugsprites/Vergilius_Skill_2.gif',
                'following-the-flow': 'assets/debugsprites/Vergilius_Skill_3.gif',
                'draw-of-the-sword': 'assets/debugsprites/Vergilius_Skill_1.gif',
                acupuncture: 'assets/debugsprites/Vergilius_Skill_2.gif',
                'yield-my-flesh': 'assets/debugsprites/Vergilius_Skill_3.gif',
                'to-claim-their-bones': 'assets/debugsprites/Vergilius_Skill_3.gif',
            },
        },
        skills: [
            {
                id: 'draw-of-the-sword',
                name: 'Draw of the Sword',
                basePower: 10,
                coinPower: 4,
                coinCount: 4,
                damageType: 'slash',
                sinType: 'pride',
                offenseLevel: 0,
                effects: [
                    { trigger: 'onSelect', type: 'modifyContext', field: 'coinPowerBonus', operation: 'add', value: 1, statusId: 'poise', minStatusPotency: 5 },
                    { trigger: 'onSelect', type: 'applyStatus', target: 'self', statusId: 'poise', potency: 0, count: 2 },
                    { trigger: 'onClashWin', type: 'applyStatus', target: 'self', statusId: 'poise', potency: 3, count: 0 },
                    { trigger: 'onHit', type: 'applyStatus', target: 'self', statusId: 'poise', potency: 3, count: 0, coinIndex: 1 },
                    { trigger: 'onHit', type: 'applyStatus', target: 'self', statusId: 'poise', potency: 3, count: 0, coinIndex: 2 },
                    { trigger: 'onHit', type: 'applyStatus', statusId: 'bleed', potency: 5, count: 1, coinIndex: 2 },
                    { trigger: 'onHit', type: 'applyStatus', statusId: 'bleed', potency: 0, count: 2, criticalOnly: true },
                ],
                borderPath: 'assets/skillborders/Pride1.png',
                description: 'Skill 1. Builds Poise Count, gains Poise on use, and bleeds targets on later coins.',
            },
            {
                id: 'acupuncture',
                name: 'Acupuncture',
                basePower: 12,
                coinPower: 4,
                coinCount: 4,
                damageType: 'slash',
                sinType: 'pride',
                offenseLevel: 1,
                effects: [
                    { trigger: 'onSelect', type: 'modifyContext', field: 'coinPowerBonus', operation: 'add', value: 1, statusId: 'poise', minStatusPotency: 7 },
                    { trigger: 'onSelect', type: 'applyStatus', target: 'self', statusId: 'poise', potency: 0, count: 3 },
                    { trigger: 'onSelect', type: 'modifyCoinMap', field: 'extraCritDamageByCoin', coinIndex: 2, value: 0.2 },
                    { trigger: 'onSelect', type: 'modifyCoinMap', field: 'extraCritDamageByCoin', coinIndex: 3, value: 0.4 },
                    { trigger: 'onClashWin', type: 'applyStatus', target: 'self', statusId: 'poise', potency: 2, count: 0 },
                    { trigger: 'onHit', type: 'applyStatus', target: 'self', statusId: 'poise', potency: 4, count: 0, coinIndex: 1 },
                    { trigger: 'onHit', type: 'applyStatus', statusId: 'bleed', potency: 0, count: 3, coinIndex: 4 },
                ],
                borderPath: 'assets/skillborders/Pride2.png',
                description: 'Skill 2. Poise-positive slash chain with escalating critical payoff.',
            },
            {
                id: 'yield-my-flesh',
                name: 'Yield My Flesh',
                basePower: 30,
                coinPower: -8,
                coinCount: 1,
                damageType: 'slash',
                sinType: 'pride',
                offenseLevel: 2,
                targeting: 'highestMaxPower',
                effects: [
                    { trigger: 'onSelect', type: 'modifyContext', field: 'damageReductionMultiplier', operation: 'setToOneMinusStatusPotencyScaled', statusId: 'poise', multiplier: 0.02, cap: 0.8 },
                    { trigger: 'onSelect', type: 'modifyContext', field: 'clashPowerBonus', operation: 'addStatusPotencyScaled', statusId: 'poise', multiplier: 1, cap: 30, direction: 'subtract' },
                    { trigger: 'onSelect', type: 'modifyCoinMap', field: 'extraCritDamageByCoin', coinIndex: 1, value: 1.5 },
                    { trigger: 'onSelect', type: 'setFollowUpSkill', skillId: 'to-claim-their-bones' },
                    { trigger: 'onClashWin', type: 'applyStatus', target: 'self', statusId: 'poise', potency: 5, count: 0 },
                    { trigger: 'onHit', type: 'modifyPhysicalResistance', target: 'opponent', damageType: 'slash', value: 1.25, coinIndex: 1, criticalOnly: true },
                    { trigger: 'onHit', type: 'modifyDefenseLevel', target: 'opponent', value: -4, coinIndex: 1, criticalOnly: true },
                ],
                borderPath: 'assets/skillborders/Pride3.png',
                description: 'Skill 3.',
            },
            {
                id: 'to-claim-their-bones',
                name: 'To Claim Their Bones',
                showInPlanner: false,
                basePower: 16,
                coinPower: 4,
                coinCount: 4,
                damageType: 'slash',
                sinType: 'pride',
                offenseLevel: 2,
                effects: [
                    { trigger: 'onSelect', type: 'modifyContext', field: 'coinPowerBonus', operation: 'add', value: 1, statusId: 'poise', minStatusPotency: 10 },
                    { trigger: 'onSelect', type: 'applyStatus', target: 'self', statusId: 'poise', potency: 0, count: 4 },
                    { trigger: 'onSelect', type: 'modifyCoinMap', field: 'critFinalPowerBonusByCoin', coinIndex: 1, value: 2 },
                    { trigger: 'onSelect', type: 'modifyCoinMap', field: 'critFinalPowerBonusByCoin', coinIndex: 2, value: 2 },
                    { trigger: 'onSelect', type: 'modifyCoinMap', field: 'critFinalPowerBonusByCoin', coinIndex: 3, value: 2 },
                    { trigger: 'onHit', type: 'applyStatus', statusId: 'bleed', potency: 10, count: 3, coinIndex: 4 },
                    { trigger: 'onHit', type: 'queueStatus', statusId: 'paralyze', count: 2, coinIndex: 4 },
                    { trigger: 'onAttackEnd', type: 'consumeStatus', target: 'self', statusId: 'poise' },
                ],
                borderPath: 'assets/skillborders/Pride3.png',
                description: 'Skill 3-2. Follow-up slash finisher that consumes all Poise at attack end.',
            },
            {
                id: 'kim-counter',
                name: 'Counter',
                skillType: 'counter',
                basePower: 12,
                coinPower: 4,
                coinCount: 1,
                damageType: 'slash',
                sinType: 'pride',
                offenseLevel: 0,
                borderPath: 'assets/skillborders/Pride1.png',
                description: 'Defense Skill. Reactively launches a one-sided counterattack after being hit.',
            },
        ],
    };

    registerUnitDefinition(bambooHattedKimDefinition);
})();
